version: '3.8'

services:
    keycloak:
        build:
            context: ./keycloak
        container_name: keycloak
        hostname: keycloak
        environment:
            DB_VENDOR: h2
            KEYCLOAK_LOGLEVEL: WARN
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
            - "8089:8080"
            - "9990:9990"

