server:
  port: 8081
spring:
  h2:
    console:
      enabled=true
  datasource: 
    url: jdbc:h2:mem:students
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties: 
      hibernate: 
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://localhost:9080/realms/Microservices

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: DEBUG
